rd.service:
  #image: services/redis:3.2
  image: redis:3.2.6-alpine
  volumes:
    - /docker/services/data/redis/:/data
    #- /docker/services/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
  expose:
    - 6379
  ports:
    #- 6789:6379
  #links:
    #- mysql:mysql
  #command: redis-server /usr/local/etc/redis/redis.conf ##
