es.service:
  image: elasticsearch:2.4.3-alpine
  volumes:
    - /docker/services/data/elasticsearch/:/usr/share/elasticsearch/data
  ports:
    - 9300:9300
    - 9200:9200
  environment:
    - Des.node.name="esNode"
    #- Des.node.master="true"
#docker run -d -v "$PWD/esdata":/usr/share/elasticsearch/data elasticsearch -Des.node.name="TestNode"

#docker run -d -v "/data/elasticsearch":/usr/share/elasticsearch/data -p 9200:9200 -p 9300:9300 elasticsearch:2.4.3-alpine -Des.node.name="TestNode"


#ERROR: bootstrap checks failed
#max virtual memory areas vm.max_map_count [200000] is too low, increase to at least [262144]
#sudo echo "vm.max_map_count=262144">>/etc/sysctl.conf
#sysctl -p
